# Generated by Django 2.1.1 on 2018-09-16 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EtsyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etsy_user_id', models.IntegerField(unique=True)),
                ('login_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('last_modified_tsz', models.DateTimeField()),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_image_id', models.IntegerField(unique=True)),
                ('rank', models.IntegerField()),
                ('url_75x75', models.CharField(max_length=200, null=True)),
                ('url_170x135', models.CharField(max_length=200, null=True)),
                ('url_570xN', models.CharField(max_length=200, null=True)),
                ('url_fullxfull', models.CharField(max_length=200)),
                ('listing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing_images', to='etsy.Listing')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_id', models.IntegerField(unique=True)),
                ('shop_name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=500, null=True)),
                ('announcement', models.CharField(max_length=500, null=True)),
                ('image_url_760x100', models.CharField(max_length=200, null=True)),
                ('icon_url_fullxfull', models.CharField(max_length=200, null=True)),
                ('last_updated_tsz', models.DateTimeField()),
                ('deleted', models.BooleanField(default=False)),
                ('etsy_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='etsy.EtsyUser')),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='main_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_image_listing', to='etsy.ListingImage'),
        ),
        migrations.AddField(
            model_name='listing',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='etsy.Shop'),
        ),
    ]
